name: diamond_tracker_mobile
version: 0.1.0
publish_to: "none"

environment:
  sdk: ">=3.2.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.5.1
  drift: ^2.19.1
  drift_flutter: ^0.1.0
  path_provider: ^2.1.3
  dio: ^5.5.0
  flutter_secure_storage: ^9.2.2
  mobile_scanner: ^5.1.3
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.11
  drift_dev: ^2.19.1

flutter:
  uses-material-design: true
